<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CantoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //'cantones
        DB::table('cantones')->insert([
            // ['id' => '1','canton' => 'San José','id_provincias' => '1',],
            // ['id' => '2','canton' => 'Escazú','id_provincias' => '1',],
            // ['id' => '3','canton' => 'Desamparados','id_provincias' => '1',],
            // ['id' => '4','canton' => 'Puriscal','id_provincias' => '1',],
            // ['id' => '5','canton' => 'Tarrazú','id_provincias' => '1',],
            // ['id' => '6','canton' => 'Aserri','id_provincias' => '1',],
            // ['id' => '7','canton' => 'Mora','id_provincias' => '1',],
            // ['id' => '8','canton' => 'Goicoechea','id_provincias' => '1',],
            // ['id' => '9','canton' => 'Santa Ana','id_provincias' => '1',],
            // ['id' => '10','canton' => 'Alajuelita','id_provincias' => '1',],
            // ['id' => '11','canton' => 'Acosta','id_provincias' => '1',],
            // ['id' => '12','canton' => 'Tibás','id_provincias' => '1',],
            // ['id' => '13','canton' => 'Moravia','id_provincias' => '1',],
            // ['id' => '14','canton' => 'Montes de Oca','id_provincias' => '1',],
            // ['id' => '15','canton' => 'Turrubares','id_provincias' => '1',],
            // ['id' => '16','canton' => 'Dota','id_provincias' => '1',],
            // ['id' => '17','canton' => 'Curridabat','id_provincias' => '1',],
            // ['id' => '18','canton' => 'Pérez Zeledón','id_provincias' => '1',],
            // ['id' => '19','canton' => 'Catedral','id_provincias' => '1',],
            // ['id' => '20','canton' => 'Alajuela','id_provincias' => '1',],
            // ['id' => '21','canton' => 'Vasquez de  Coronado','id_provincias' => '1',],
            // ['id' => '22','canton' => 'León Cortes Castro','id_provincias' => '1',],
            // ['id' => '23','canton' => 'Gonzalez','id_provincias' => '1',],
            // ['id' => '24','canton' => 'San Sebastían','id_provincias' => '1',],
            // ['id' => '25','canton' => 'Santiago','id_provincias' => '1',],
            // ['id' => '1','canton' => 'Heredia','id_provincias' => '2',],
            // ['id' => '2','canton' => 'Barba','id_provincias' => '2',],
            // ['id' => '3','canton' => 'Aurora','id_provincias' => '2',],
            // ['id' => '4','canton' => 'Santa Bárbara','id_provincias' => '2',],
            // ['id' => '6','canton' => 'San Rafael','id_provincias' => '2',],
            // ['id' => '7','canton' => 'San Isidro','id_provincias' => '2',],
            // ['id' => '8','canton' => 'San Rafael','id_provincias' => '2',],
            // ['id' => '9','canton' => 'Flores','id_provincias' => '2',],
            // ['id' => '10','canton' => 'Sarapiqui','id_provincias' => '2',],
            // ['id' => '13','canton' => 'San  Pablo','id_provincias' => '2',],
            // ['id' => '14','canton' => 'Santo Domingo','id_provincias' => '2',],
            // ['id' => '15','canton' => 'San Joaquín','id_provincias' => '2',],
            // ['id' => '1','canton' => 'Alajuela','id_provincias' => '3',],
            // ['id' => '2','canton' => 'San Carlos','id_provincias' => '3',],
            // ['id' => '3','canton' => 'Grecia','id_provincias' => '3',],
            // ['id' => '4','canton' => 'San Mateo','id_provincias' => '3',],
            // ['id' => '5','canton' => 'Atenas','id_provincias' => '3',],
            // ['id' => '6','canton' => 'Naranjo','id_provincias' => '3',],
            // ['id' => '7','canton' => 'Palmares','id_provincias' => '3',],
            // ['id' => '8','canton' => 'Poás','id_provincias' => '3',],
            // ['id' => '9','canton' => 'Orotina','id_provincias' => '3',],
            // ['id' => '10','canton' => 'San Carlos','id_provincias' => '3',],
            // ['id' => '11','canton' => 'Zarcero','id_provincias' => '3',],
            // ['id' => '12','canton' => 'Sarchí','id_provincias' => '3',],
            // ['id' => '13','canton' => 'Upala','id_provincias' => '3',],
            // ['id' => '14','canton' => 'Los Chiles','id_provincias' => '3',],
            // ['id' => '15','canton' => 'Guatuso','id_provincias' => '3',],
            // ['id' => '16','canton' => 'Rio Cuarto','id_provincias' => '3',],
            // ['id' => '17','canton' => 'Centro','id_provincias' => '3',],
            // ['id' => '1','canton' => 'Liberia','id_provincias' => '4',],
            // ['id' => '2','canton' => 'Nicoya','id_provincias' => '4',],
            // ['id' => '3','canton' => 'Santa Cruz','id_provincias' => '4',],
            // ['id' => '4','canton' => 'Bagaces','id_provincias' => '4',],
            // ['id' => '5','canton' => 'Carrillo','id_provincias' => '4',],
            // ['id' => '6','canton' => 'Cañas','id_provincias' => '4',],
            // ['id' => '7','canton' => 'Tilarán','id_provincias' => '4',],
            // ['id' => '8','canton' => 'Nandayure','id_provincias' => '4',],
            // ['id' => '9','canton' => 'La Cruz','id_provincias' => '4',],
            // ['id' => '10','canton' => 'Aguirre','id_provincias' => '4',],
            // ['id' => '11','canton' => 'Abangares','id_provincias' => '4',],
            // ['id' => '1','canton' => 'Puntarenas','id_provincias' => '5',],
            // ['id' => '2','canton' => 'Esparza','id_provincias' => '5',],
            // ['id' => '3','canton' => 'Buenos Aires','id_provincias' => '5',],
            // ['id' => '4','canton' => 'Montes de Oro','id_provincias' => '5',],
            // ['id' => '5','canton' => 'Osa','id_provincias' => '5',],
            // ['id' => '6','canton' => 'Quepos','id_provincias' => '5',],
            // ['id' => '7','canton' => 'Golfito','id_provincias' => '5',],
            // ['id' => '8','canton' => 'Coto Brus','id_provincias' => '5',],
            // ['id' => '9','canton' => 'Parrita','id_provincias' => '5',],
            // ['id' => '10','canton' => 'Corredores','id_provincias' => '5',],
            // ['id' => '11','canton' => 'Garabito','id_provincias' => '5',],
            // ['id' => '12','canton' => 'Monteverde','id_provincias' => '5',],
            // ['id' => '13','canton' => 'Puerto Jiménez','id_provincias' => '5',],
            // ['id' => '14','canton' => 'El Tigre','id_provincias' => '5',],
            // ['id' => '15','canton' => 'Barrancas','id_provincias' => '5',],
            // ['id' => '1','canton' => 'Limón','id_provincias' => '6',],
            // ['id' => '2','canton' => 'Pococi','id_provincias' => '6',],
            // ['id' => '3','canton' => 'Siquirres','id_provincias' => '6',],
            // ['id' => '4','canton' => 'Talamanca','id_provincias' => '6',],
            // ['id' => '5','canton' => 'Matina','id_provincias' => '6',],
            // ['id' => '6','canton' => 'Guácimo','id_provincias' => '6',],
            // ['id' => '7','canton' => 'Germania','id_provincias' => '6',],
            // ['id' => '8','canton' => 'Central','id_provincias' => '6',],
            // ['id' => '1','canton' => 'Cartago','id_provincias' => '7',],
            // ['id' => '2','canton' => 'Paraiso','id_provincias' => '7',],
            // ['id' => '3','canton' => 'Tres Rios','id_provincias' => '7',],
            // ['id' => '4','canton' => 'Juan Viñas','id_provincias' => '7',],
            // ['id' => '5','canton' => 'Turrialba','id_provincias' => '7',],
            // ['id' => '6','canton' => 'Alvarado','id_provincias' => '7',],
            // ['id' => '7','canton' => 'Oreamuno','id_provincias' => '7',],
            // ['id' => '8','canton' => 'El Guarco','id_provincias' => '7',],
            // ['id' => '9','canton' => 'Oriental','id_provincias' => '7',],
            // ['id' => '10','canton' => 'Occidental','id_provincias' => '7',],
            // ['id' => '11','canton' => 'Carmen','id_provincias' => '7',],
            // ['id' => '12','canton' => 'San Nicolas','id_provincias' => '7',],
            // ['id' => '13','canton' => 'La Unión','id_provincias' => '7',],

            ['id' => '1', 'CantonNumber' => '1', 'canton' => 'San José', 'id_provincias' => '1'],
            ['id' => '2', 'CantonNumber' => '2', 'canton' => 'Escazú', 'id_provincias' => '1'],
            ['id' => '3', 'CantonNumber' => '3', 'canton' => 'Desamparados', 'id_provincias' => '1'],
            ['id' => '4', 'CantonNumber' => '4', 'canton' => 'Puriscal', 'id_provincias' => '1'],
            ['id' => '5', 'CantonNumber' => '5', 'canton' => 'Tarrazú', 'id_provincias' => '1'],
            ['id' => '6', 'CantonNumber' => '6', 'canton' => 'Aserri', 'id_provincias' => '1'],
            ['id' => '7', 'CantonNumber' => '7', 'canton' => 'Mora', 'id_provincias' => '1'],
            ['id' => '8', 'CantonNumber' => '8', 'canton' => 'Goicoechea', 'id_provincias' => '1'],
            ['id' => '9', 'CantonNumber' => '9', 'canton' => 'Santa Ana', 'id_provincias' => '1'],
            ['id' => '10', 'CantonNumber' => '10', 'canton' => 'Alajuelita', 'id_provincias' => '1'],
            ['id' => '11', 'CantonNumber' => '11', 'canton' => 'Acosta', 'id_provincias' => '1'],
            ['id' => '12', 'CantonNumber' => '12', 'canton' => 'Tibás', 'id_provincias' => '1'],
            ['id' => '13', 'CantonNumber' => '13', 'canton' => 'Moravia', 'id_provincias' => '1'],
            ['id' => '14', 'CantonNumber' => '14', 'canton' => 'Montes de Oca', 'id_provincias' => '1'],
            ['id' => '15', 'CantonNumber' => '15', 'canton' => 'Turrubares', 'id_provincias' => '1'],
            ['id' => '16', 'CantonNumber' => '16', 'canton' => 'Dota', 'id_provincias' => '1'],
            ['id' => '17', 'CantonNumber' => '17', 'canton' => 'Curridabat', 'id_provincias' => '1'],
            ['id' => '18', 'CantonNumber' => '18', 'canton' => 'Pérez Zeledón', 'id_provincias' => '1'],
            ['id' => '19', 'CantonNumber' => '19', 'canton' => 'Catedral', 'id_provincias' => '1'],
            ['id' => '20', 'CantonNumber' => '20', 'canton' => 'Alajuela', 'id_provincias' => '1'],
            ['id' => '21', 'CantonNumber' => '21', 'canton' => 'Vasquez de Coronado', 'id_provincias' => '1'],
            ['id' => '22', 'CantonNumber' => '22', 'canton' => 'León Cortes Castro', 'id_provincias' => '1'],
            ['id' => '23', 'CantonNumber' => '23', 'canton' => 'Gonzalez', 'id_provincias' => '1'],
            ['id' => '24', 'CantonNumber' => '24', 'canton' => 'San Sebastían', 'id_provincias' => '1'],
            ['id' => '25', 'CantonNumber' => '25', 'canton' => 'Santiago', 'id_provincias' => '1'],
            ['id' => '26', 'CantonNumber' => '1', 'canton' => 'Heredia', 'id_provincias' => '2'],
            ['id' => '27', 'CantonNumber' => '2', 'canton' => 'Barba', 'id_provincias' => '2'],
            ['id' => '28', 'CantonNumber' => '3', 'canton' => 'Aurora', 'id_provincias' => '2'],
            ['id' => '29', 'CantonNumber' => '4', 'canton' => 'Santa Bárbara', 'id_provincias' => '2'],
            ['id' => '30', 'CantonNumber' => '6', 'canton' => 'San Rafael', 'id_provincias' => '2'],
            ['id' => '31', 'CantonNumber' => '7', 'canton' => 'San Isidro', 'id_provincias' => '2'],
            ['id' => '32', 'CantonNumber' => '8', 'canton' => 'San Rafael', 'id_provincias' => '2'],
            ['id' => '33', 'CantonNumber' => '9', 'canton' => 'Flores', 'id_provincias' => '2'],
            ['id' => '34', 'CantonNumber' => '10', 'canton' => 'Sarapiqui', 'id_provincias' => '2'],
            ['id' => '35', 'CantonNumber' => '13', 'canton' => 'San Pablo', 'id_provincias' => '2'],
            ['id' => '36', 'CantonNumber' => '14', 'canton' => 'Santo Domingo', 'id_provincias' => '2'],
            ['id' => '37', 'CantonNumber' => '15', 'canton' => 'San Joaquín', 'id_provincias' => '2'],
            ['id' => '38', 'CantonNumber' => '1', 'canton' => 'Alajuela', 'id_provincias' => '3'],
            ['id' => '39', 'CantonNumber' => '2', 'canton' => 'San Carlos', 'id_provincias' => '3'],
            ['id' => '40', 'CantonNumber' => '3', 'canton' => 'Grecia', 'id_provincias' => '3'],
            ['id' => '41', 'CantonNumber' => '4', 'canton' => 'San Mateo', 'id_provincias' => '3'],
            ['id' => '42', 'CantonNumber' => '5', 'canton' => 'Atenas', 'id_provincias' => '3'],
            ['id' => '43', 'CantonNumber' => '6', 'canton' => 'Naranjo', 'id_provincias' => '3'],
            ['id' => '44', 'CantonNumber' => '7', 'canton' => 'Palmares', 'id_provincias' => '3'],
            ['id' => '45', 'CantonNumber' => '8', 'canton' => 'Poás', 'id_provincias' => '3'],
            ['id' => '46', 'CantonNumber' => '9', 'canton' => 'Orotina', 'id_provincias' => '3'],
            ['id' => '47', 'CantonNumber' => '10', 'canton' => 'San Carlos', 'id_provincias' => '3'],
            ['id' => '48', 'CantonNumber' => '11', 'canton' => 'Zarcero', 'id_provincias' => '3'],
            ['id' => '49', 'CantonNumber' => '12', 'canton' => 'Sarchí', 'id_provincias' => '3'],
            ['id' => '50', 'CantonNumber' => '13', 'canton' => 'Upala', 'id_provincias' => '3'],
            ['id' => '51', 'CantonNumber' => '14', 'canton' => 'Los Chiles', 'id_provincias' => '3'],
            ['id' => '52', 'CantonNumber' => '15', 'canton' => 'Guatuso', 'id_provincias' => '3'],
            ['id' => '53', 'CantonNumber' => '16', 'canton' => 'Rio Cuarto', 'id_provincias' => '3'],
            ['id' => '54', 'CantonNumber' => '17', 'canton' => 'Centro', 'id_provincias' => '3'],
            ['id' => '55', 'CantonNumber' => '1', 'canton' => 'Liberia', 'id_provincias' => '4'],
            ['id' => '56', 'CantonNumber' => '2', 'canton' => 'Nicoya', 'id_provincias' => '4'],
            ['id' => '57', 'CantonNumber' => '3', 'canton' => 'Santa Cruz', 'id_provincias' => '4'],
            ['id' => '58', 'CantonNumber' => '4', 'canton' => 'Bagaces', 'id_provincias' => '4'],
            ['id' => '59', 'CantonNumber' => '5', 'canton' => 'Carrillo', 'id_provincias' => '4'],
            ['id' => '60', 'CantonNumber' => '6', 'canton' => 'Cañas', 'id_provincias' => '4'],
            ['id' => '61', 'CantonNumber' => '7', 'canton' => 'Tilarán', 'id_provincias' => '4'],
            ['id' => '62', 'CantonNumber' => '8', 'canton' => 'Nandayure', 'id_provincias' => '4'],
            ['id' => '63', 'CantonNumber' => '9', 'canton' => 'La Cruz', 'id_provincias' => '4'],
            ['id' => '64', 'CantonNumber' => '10', 'canton' => 'Aguirre', 'id_provincias' => '4'],
            ['id' => '65', 'CantonNumber' => '11', 'canton' => 'Abangares', 'id_provincias' => '4'],
            ['id' => '66', 'CantonNumber' => '1', 'canton' => 'Puntarenas', 'id_provincias' => '5'],
            ['id' => '67', 'CantonNumber' => '2', 'canton' => 'Esparza', 'id_provincias' => '5'],
            ['id' => '68', 'CantonNumber' => '3', 'canton' => 'Buenos Aires', 'id_provincias' => '5'],
            ['id' => '69', 'CantonNumber' => '4', 'canton' => 'Montes de Oro', 'id_provincias' => '5'],
            ['id' => '70', 'CantonNumber' => '5', 'canton' => 'Osa', 'id_provincias' => '5'],
            ['id' => '71', 'CantonNumber' => '6', 'canton' => 'Quepos', 'id_provincias' => '5'],
            ['id' => '72', 'CantonNumber' => '7', 'canton' => 'Golfito', 'id_provincias' => '5'],
            ['id' => '73', 'CantonNumber' => '8', 'canton' => 'Coto Brus', 'id_provincias' => '5'],
            ['id' => '74', 'CantonNumber' => '9', 'canton' => 'Parrita', 'id_provincias' => '5'],
            ['id' => '75', 'CantonNumber' => '10', 'canton' => 'Corredores', 'id_provincias' => '5'],
            ['id' => '76', 'CantonNumber' => '11', 'canton' => 'Garabito', 'id_provincias' => '5'],
            ['id' => '77', 'CantonNumber' => '12', 'canton' => 'Monteverde', 'id_provincias' => '5'],
            ['id' => '78', 'CantonNumber' => '13', 'canton' => 'Puerto Jiménez', 'id_provincias' => '5'],
            ['id' => '79', 'CantonNumber' => '14', 'canton' => 'El Tigre', 'id_provincias' => '5'],
            ['id' => '80', 'CantonNumber' => '15', 'canton' => 'Barrancas', 'id_provincias' => '5'],
            ['id' => '81', 'CantonNumber' => '1', 'canton' => 'Limón', 'id_provincias' => '6'],
            ['id' => '82', 'CantonNumber' => '2', 'canton' => 'Pococi', 'id_provincias' => '6'],
            ['id' => '83', 'CantonNumber' => '3', 'canton' => 'Siquirres', 'id_provincias' => '6'],
            ['id' => '84', 'CantonNumber' => '4', 'canton' => 'Talamanca', 'id_provincias' => '6'],
            ['id' => '85', 'CantonNumber' => '5', 'canton' => 'Matina', 'id_provincias' => '6'],
            ['id' => '86', 'CantonNumber' => '6', 'canton' => 'Guácimo', 'id_provincias' => '6'],
            ['id' => '87', 'CantonNumber' => '7', 'canton' => 'Germania', 'id_provincias' => '6'],
            ['id' => '88', 'CantonNumber' => '8', 'canton' => 'Central', 'id_provincias' => '6'],
            ['id' => '89', 'CantonNumber' => '1', 'canton' => 'Cartago', 'id_provincias' => '7'],
            ['id' => '90', 'CantonNumber' => '2', 'canton' => 'Paraiso', 'id_provincias' => '7'],
            ['id' => '91', 'CantonNumber' => '3', 'canton' => 'Tres Rios', 'id_provincias' => '7'],
            ['id' => '92', 'CantonNumber' => '4', 'canton' => 'Juan Viñas', 'id_provincias' => '7'],
            ['id' => '93', 'CantonNumber' => '5', 'canton' => 'Turrialba', 'id_provincias' => '7'],
            ['id' => '94', 'CantonNumber' => '6', 'canton' => 'Alvarado', 'id_provincias' => '7'],
            ['id' => '95', 'CantonNumber' => '7', 'canton' => 'Oreamuno', 'id_provincias' => '7'],
            ['id' => '96', 'CantonNumber' => '8', 'canton' => 'El Guarco', 'id_provincias' => '7'],
            ['id' => '97', 'CantonNumber' => '9', 'canton' => 'Oriental', 'id_provincias' => '7'],
            ['id' => '98', 'CantonNumber' => '10', 'canton' => 'Occidental', 'id_provincias' => '7'],
            ['id' => '99', 'CantonNumber' => '11', 'canton' => 'Carmen', 'id_provincias' => '7'],
            ['id' => '100', 'CantonNumber' => '12', 'canton' => 'San Nicolas', 'id_provincias' => '7'],
            ['id' => '101', 'CantonNumber' => '13', 'canton' => 'La Unión', 'id_provincias' => '7'],

        ]);
    }
}
